config/routes.rb
Commers::Application.routes.draw do

  get "sitemap/index"
  get "f/:filename", to: "file_storage#show"
  get "template/stylesheets/:key", to: "template#stylesheets"
  get "editable/stylesheets/:key", to: "editable#stylesheets"

  # メルマガユーザーエクスポート
  resources :mailmagazine_export, only: [:index]

  namespace :landing, path: 'land' do
    get :oioil, action: :oioil
  end

  # 表側ユーザ
  devise_scope :consumer do
    get "complete", to: "consumers/registrations#complete"
  end
  devise_for :consumers,
    path: 'mypage',
    controllers: {
      sessions: "sessions",
      registrations: "consumers/registrations",
      confirmations: "consumers/confirmations"
    }

  # トップページ
  controller :welcome do
    root action: "index"
    get "introduction", action: "introduction"
    get "about", action: "about"
    get "utilization", action: "utilization"
    get "faq", action: "faq"
    get "sitemap", action: "sitemap"
    get "company", action: "company"
    get "tradeinfo", action: "tradeinfo"
    get "privacypolicy", action: "privacypolicy"
    get "shops", action: "shops"
  end

  namespace :mypage do
    root action: :information
    patch "information", action: :update_information
  end

  # お問い合わせ
  controller :contact do
    get "contact", action: :new
    post "contact", action: :create
  end

  # 注文履歴
  resources :orders, only: [:index, :show, :edit, :update]

  # News
  resources :topics, only: [:index, :show]

  # プレスリリース
  resources :press_releases, only: [:index]

  # News
  resources :news_releases, only: [:index, :show]

  # 詳細ページ
  resources :products, only: [:index, :show] do
    collection do
      get 'newitems'
      get 'ranking'
    end
  end

  # 商品一覧
  namespace :catalog do
    get ":action/:id"
  end

  # レビュー
  resources :reviews, only: [:create]

  # カート
  resources :carts, only: [:index] do
    collection do
      post "add"
      patch "increment"
      patch "decrement"
      delete "remove"
    end
  end

  # 注文
  namespace :cashier do
    get "", action: "index"

    get "sample"
    patch "sample", action: "sample_create"

    get "shipment"
    patch "shipment", action: "shipment_create"

    get "payment"
    patch "payment", action: "payment_create"

    get "confirm"
    patch "confirm", action: "confirm_create"

    get "complete"
  end

  # サロン情報
  resources :salons, only: [:index]

  # 裏側
  namespace :admin, module: :administration do

    # Admin root
    root to: "dashboard#index"

    # Setting
    resource :setting

    # Session
    delete "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    post "login" => "sessions#create"

    # プレスリリース
    resources :press_releases

    # Topics
    resources :topics

    # News
    resources :news_releases

    # 商品マスタ管理
    resources :products
    resources :categories
    resources :serieses
    resources :solutions

    # お客様の声
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]

    # 注文管理
    resources :orders, except: [:new, :create] do
      collection do
        post :update_status
      end
    end

    # 売上一覧
    resources :sales, only: [:index] do
      collection do
        get :products
      end
    end

    # 裏側ユーザ管理
    resources :administrators

    resources :consumers

    # デザインテンプレート編集
    resources :templates

    # ページ編集
    resources :pages

    # File Storage
    resources :file_storages

    # 代理店管理
    resources :agencies

    # マージン管理
    resources :margins, only: [:index, :show, :edit, :update]

    # サロン管理
    resources :salons

    # 情報編集
    resource :information, only: [:show, :edit, :update]

    # 報酬確認画面
    get "reward", to: "reward#show"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Authority::Abilities
  self.authorizer_name = 'AdministrationAuthorizer'

  include Confirmable

  extend FriendlyId
  friendly_id :name

  has_and_belongs_to_many :serieses
  has_and_belongs_to_many :categories, join_table: :products_categories
  has_and_belongs_to_many :solutions

  belongs_to :template
  belongs_to :page

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true, limit: 4

  belongs_to :plusone, class_name: 'Product'

  has_many :reviews

  has_many :margins, class_name: 'ProductMargin'

  scope :available, -> { where(sample: false, invisible: false) }
  scope :stocked, -> { where('stock > 0') }
  scope :sample, -> { where(sample: true) }

  scope :new_items, -> { available.where(new_item: true).limit(3) }
  scope :ranking, -> { available.order(ranking: :desc).limit(3) }

  serialize :recommendation_ids

  after_initialize :set_default_values
  def set_default_values
    self.backmargin_salon ||= 30
    self.backmargin_agency ||= 28
  end

  def series
    self.serieses.first
  end

  def category
    self.categories.first
  end

  def image *args
    (self.photos.first || self.photos.new).image *args
  end

  def admin_name
    if self.sample
      "#{name} <サンプル>"
    else
      name
    end
  end

  def view_price
    (self.price * Setting.tax_rate).to_i
  end

  def view_price= price
    self.price = (price.to_f / Setting.tax_rate).to_i
  end

  def increase amount
    stock = self.stock + amount
    update_column :stock, stock
  end

  def decrease amount
    stock = self.stock - amount
    raise DecreasingError if stock < 0
    # TODO: 一定数以下になったら通知する
    update_column :stock, stock
  end

  def self.last_updated_at
    self.order(updated_at: :desc).first.updated_at
  end

  def recommendations
    if self.recommendation_ids
      Product.find(self.recommendation_ids)
    else
      Product.available.limit(4).load
    end
  end

  def showable?
    !self.sample
  end

  def singleton?
    self.series.singleton == self
  end

  def label_simple
    self.label.gsub(/[＊\*]\d/, '')
  end

  def backmargin_agency
  end

  def backmargin_salon
  end

  class DecreasingError < ActiveRecord::ActiveRecordError
  end
end

app/controllers/administration/administrators_controller.rb
module Administration
  class AdministratorsController < BaseController
    authorize_actions_for Administrator

    before_action :set_administrator, only: [:show, :edit, :update, :destroy]

    # GET /administration/administrators
    # GET /administration/administrators.json
    def index
      @administrators = Administrator.all
    end

    # GET /administration/administrators/1
    # GET /administration/administrators/1.json
    def show
    end

    # GET /administration/administrators/new
    def new
      @administrator = Administrator.new
    end

    # GET /administration/administrators/1/edit
    def edit
    end

    # POST /administration/administrators
    # POST /administration/administrators.json
    def create
      @administrator = Administrator.new(administrator_params)

      respond_to do |format|
        if @administrator.save
          format.html { redirect_to [:admin, @administrator], notice: rmt(:successfully, :created, @administrator) }
          format.json { render action: 'show', status: :created, location: [:admin, @administrator] }
        else
          format.html { render action: 'new' }
          format.json { render json: @administrator.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /administration/administrators/1
    # PATCH/PUT /administration/administrators/1.json
    def update
      respond_to do |format|
        if @administrator.update(administrator_params)
          format.html { redirect_to [:admin, @administrator], notice: rmt(:successfully, :updated, @administrator) }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @administrator.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /administration/administrators/1
    # DELETE /administration/administrators/1.json
    def destroy
      @administrator.destroy
      respond_to do |format|
        format.html { redirect_to admin_administrators_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:username, :password, :password_confirmation)
    end
  end
end

app/controllers/administration/agencies_controller.rb
module Administration
  class AgenciesController < BaseController
    authorize_actions_for Agency

    before_action :set_agency, only: [:show, :edit, :update, :destroy]

    # GET /administration/agencies
    # GET /administration/agencies.json
    def index
      @agencies = Agency.all
    end

    # GET /administration/agencies/1
    # GET /administration/agencies/1.json
    def show
    end

    # GET /administration/agencies/new
    def new
      @agency = Agency.new
    end

    # GET /administration/agencies/1/edit
    def edit
    end

    # POST /administration/agencies
    # POST /administration/agencies.json
    def create
      @agency = Agency.new(agency_params)

      respond_to do |format|
        if @agency.save
          format.html { redirect_to [:admin, @agency], notice: rmt(:successfully, :created, @agency) }
          format.json { render action: 'show', status: :created, location: [:admin, @agency] }
        else
          format.html { render action: 'new' }
          format.json { render json: @agency.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /administration/agencies/1
    # PATCH/PUT /administration/agencies/1.json
    def update
      respond_to do |format|
        if @agency.update(agency_params)
          format.html { redirect_to [:admin, @agency], notice: rmt(:successfully, :updated, @agency) }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @agency.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /administration/agencies/1
    # DELETE /administration/agencies/1.json
    def destroy
      @agency.destroy
      respond_to do |format|
        format.html { redirect_to admin_agencies_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params
        .require(:agency)
        .permit(
          :name,
          :backmargin_agency,
          :backmargin_salon,
          :salon_csv,
          administrator_attributes: [
            :username,
            :password,
            :password_confirmation
          ]
      )
    end
  end
end

app/controllers/administration/base_controller.rb
require "base64"

module Administration
  class BaseController < ApplicationController
    protect_from_forgery with: :exception

    layout "administration"

    before_filter :require_login

    helper_method :current_administrator

    helper_method :resource_name
    helper_method :resource

    def current_ability
      @current_ability ||= AdministratorAbility.new(current_administrator)
    end

    private

    def self.confirmation! resource_name
      @@resource_name = resource_name.to_s
      before_action :confirmation!, only: [:create, :update]
    end

    def confirmation!
      if params[:confirm] && resource.confirmable?
        session[:confirmation] ||= {}
        session[:confirmation][@@resource_name] = base64_encode(resource_params)
        render "confirm" and return false
      end
      if session[:confirmation] && session[:confirmation][@@resource_name]
        self.params = (params || {}).merge(@@resource_name => base64_decode(session[:confirmation][@@resource_name]))
        session.delete(:confirmation)
      end
    end

    def base64_encode hash
      ::Hash.new.tap do |new_hash|
        hash.each do |key, val|
          new_hash[key] =
            case val
            when ::ActionDispatch::Http::UploadedFile
              "exdata:#{val.content_type};#{val.original_filename};#{Base64.encode64(val.tempfile.read)}"
            when ::Hash
              base64_encode val
            else
              val
            end
        end
      end
    end

    def base64_decode hash
      hash
    end

    def resource_params
      send "#{@@resource_name}_params"
    end

    def resource
      @@resource ||= (
        if klass = @@resource_name.capitalize.constantize
          if params[:id]
            klass.find(params[:id])
          else
            klass.new
          end
      end
      ).tap do |resource|
        if params = resource_params
          resource.attributes =  params
        end
      end
    end

    def not_authenticated
      redirect_to admin_login_path, notice: I18n.t('administration_session.sign_in_required')
    end
  end
end

app/controllers/administration/categories_controller.rb
module Administration
  class CategoriesController < BaseController
    authorize_actions_for Category

    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /administration/categories
    # GET /administration/categories.json
    def index
      @categories = Category.all
    end

    # GET /administration/categories/1
    # GET /administration/categories/1.json
    def show
    end

    # GET /administration/categories/new
    def new
      @category = Category.new
    end

    # GET /administration/categories/1/edit
    def edit
    end

    # POST /administration/categories
    # POST /administration/categories.json
    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to [:admin, @category], notice: rmt(:successfully, :created, @category) }
          format.json { render action: 'show', status: :created, location: [:admin, @category] }
        else
          format.html { render action: 'new' }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /administration/categories/1
    # PATCH/PUT /administration/categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to [:admin, @category], notice: rmt(:successfully, :updated, @category) }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /administration/categories/1
    # DELETE /administration/categories/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to admin_categories_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/administration/consumers_controller.rb
module Administration
  class ConsumersController < BaseController
    before_action :set_consumer, only: [:show, :edit, :update, :destroy]

    # GET /administration/consumers
    # GET /administration/consumers.json
    def index
      @q = Consumer.search(params[:q])
      @consumers = @q.result(distinct: true)
      respond_to do |fmt|
        fmt.html { @consumers = @consumers.page(params[:page]).per(20) }
        fmt.csv
      end
    end

    # GET /administration/consumers/1
    # GET /administration/consumers/1.json
    def show
    end

    # GET /administration/consumers/new
    def new
      @consumer = Consumer.new
    end

    # GET /administration/consumers/1/edit
    def edit
    end

    # POST /administration/consumers
    # POST /administration/consumers.json
    def create
      @consumer = Consumer.new(consumer_params)

      respond_to do |format|
        if @consumer.save
          format.html { redirect_to [:admin, @consumer], notice: 'Consumer was successfully created.' }
          format.json { render action: 'show', status: :created, location: [:admin, @consumer] }
        else
          format.html { render action: 'new' }
          format.json { render json: @consumer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /administration/consumers/1
    # PATCH/PUT /administration/consumers/1.json
    def update
      respond_to do |format|
        if @consumer.update(consumer_params)
          format.html { redirect_to [:admin, @consumer], notice: 'Consumer was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @consumer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /administration/consumers/1
    # DELETE /administration/consumers/1.json
    def destroy
      @consumer.destroy
      respond_to do |format|
        format.html { redirect_to admin_consumers_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumer
      @consumer = Consumer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumer_params
      params[:consumer]
    end
  end
end

app/views/administration/products/_form.html.slim
= form_for [:admin, @product], html: { class: 'easy-form', multipart: true } do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  = hidden_field_tag :confirm, true

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :invisible
    = f.check_box :invisible

  .field
    = f.label :label
    = f.text_field :label

  .field
    = f.label :refnum
    = f.text_field :refnum

  .field
    = f.label :price
    = f.number_field :price

  = f.limited_fields_for :photos do |f|
    fieldset
      legend 商品画像
      = image_tag f.object.image.url(:thumb) if f.object.image.present?
      = f.label :image
      = f.file_field :image
      p
        | Delete:
        = f.check_box :_destroy, checked: !f.object.persisted?

  .field
    = f.label :capacity
    = f.text_field :capacity

  .field
    = f.label :detail
    = f.text_area :detail

  .field
    = f.label :small_detail
    = f.text_area :small_detail

  .field
    = f.label :stock
    = f.number_field :stock

  fieldset
    legend ブランド別
    - Series.all.each do |series|
      .item
        = label_tag "product_series_ids_#{series.id}" do
          = check_box_tag "product[series_ids][]", series.id, f.object.series_ids.include?(series.id), id: "product_series_ids_#{series.id}"
          = series.name

  fieldset
    legend カテゴリー別
    - Category.all.each do |category|
      .item
        = label_tag "product_category_ids_#{category.id}" do
          = check_box_tag "product[category_ids][]", category.id, f.object.category_ids.include?(category.id), id: "product_category_ids_#{category.id}"
          = category.name

  fieldset
    legend お悩み別
    - Solution.all.each do |solution|
      .item
        = label_tag "product_solution_ids_#{solution.id}" do
          = check_box_tag "product[solution_ids][]", solution.id, f.object.solution_ids.include?(solution.id), id: "product_solution_ids_#{solution.id}"
          = solution.name

  .field
    = f.label :template
    = f.collection_select :template_id, ::Template.all, :id, :name, include_blank: true

  .field
    = f.label :page
    = f.collection_select :page_id, Page.all, :id, :title, include_blank: true

  .field
    = f.label :sample
    = f.check_box :sample

  .field
    = f.label :backmargin_salon
    = f.number_field :backmargin_salon

  .field
    = f.label :backmargin_agency
    = f.number_field :backmargin_agency

  .field
    = f.label :type
    = f.select :type, [Product::OiOil, Product::Authentic, Product::MoreInside, Product::Naturaltech].map{|m| [m.model_name.human, m.name] }

  .field
    = f.label :kind
    = f.text_field :kind

  .field
    = f.label :ingredient
    = f.text_field :ingredient

  .field
    = f.label :parts
    = f.text_field :parts

  .field
    = f.label :label_color
    = f.text_field :label_color

  .field
    = f.label :annotation
    = f.text_area :annotation

  .field
    = f.label :annotation_mobile
    = f.text_area :annotation_mobile

  .field
    = f.label :new_item
    = f.text_field :new_item

  .field
    = f.label :ranking
    = f.text_field :ranking

  .field
    = f.label :plusone
    = f.select :plusone_id, Product.available.pluck(:name, :id)

  .actions = f.submit '保存'

app/views/administration/products/_sample.html.slim
.products
  .basic-information
    .main-image = image_tag @product.image.url(:medium)
    .information
      .name
        h1 = @product.name
        p.label = "【#{@product.label}】"

app/views/administration/products/confirm.html.slim
h1 Confirm

app/views/administration/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', [:admin, @product]
'|
= link_to 'Back', admin_products_path

app/views/administration/products/index.html.slim
h1 商品一覧

p = link_to '新規追加', new_admin_product_path

h2 通常商品
table
  tr
    th.w90 名称
    th.w10 在庫

  - @products.where(sample: false).each do |product|
    tr
      td.w90 = link_to product.name, [:admin, product]
      td.w10 = product.stock

h2 サンプル
table
  tr
    th.w90 名称
    th.w10 在庫

  - @products.sample.each do |product|
    tr
      td.w90 = link_to product.name, [:admin, product]
      td.w10 = product.stock


br

app/views/administration/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', admin_products_path

app/views/administration/products/show.html.slim
p
  = link_to '編集', edit_admin_product_path(@product)
  '|
  = link_to '削除', [:admin, @product], data: { confirm: 'Are you sure?' }, method: :delete
  '|
  = link_to '戻る', admin_products_path

br

- if @product.sample
  = render 'sample'
- else
  .products = render 'product'