config/routes.rb
Commers::Application.routes.draw do

  get "sitemap/index"
  get "f/:filename", to: "file_storage#show"
  get "template/stylesheets/:key", to: "template#stylesheets"
  get "editable/stylesheets/:key", to: "editable#stylesheets"

  # メルマガユーザーエクスポート
  resources :mailmagazine_export, only: [:index]

  namespace :landing, path: 'land' do
    get :oioil, action: :oioil
  end

  # 表側ユーザ
  devise_scope :consumer do
    get "complete", to: "consumers/registrations#complete"
  end
  devise_for :consumers,
    path: 'mypage',
    controllers: {
      sessions: "sessions",
      registrations: "consumers/registrations",
      confirmations: "consumers/confirmations"
    }

  # トップページ
  controller :welcome do
    root action: "index"
    get "introduction", action: "introduction"
    get "about", action: "about"
    get "utilization", action: "utilization"
    get "faq", action: "faq"
    get "sitemap", action: "sitemap"
    get "company", action: "company"
    get "tradeinfo", action: "tradeinfo"
    get "privacypolicy", action: "privacypolicy"
    get "shops", action: "shops"
  end

  namespace :mypage do
    root action: :information
    patch "information", action: :update_information
  end

  # お問い合わせ
  controller :contact do
    get "contact", action: :new
    post "contact", action: :create
  end

  # 注文履歴
  resources :orders, only: [:index, :show, :edit, :update]

  # News
  resources :topics, only: [:index, :show]

  # プレスリリース
  resources :press_releases, only: [:index]

  # News
  resources :news_releases, only: [:index, :show]

  # 詳細ページ
  resources :products, only: [:index, :show] do
    collection do
      get 'newitems'
      get 'ranking'
    end
  end

  # 商品一覧
  namespace :catalog do
    get ":action/:id"
  end

  # レビュー
  resources :reviews, only: [:create]

  # カート
  resources :carts, only: [:index] do
    collection do
      post "add"
      patch "increment"
      patch "decrement"
      delete "remove"
    end
  end

  # 注文
  namespace :cashier do
    get "", action: "index"

    get "sample"
    patch "sample", action: "sample_create"

    get "shipment"
    patch "shipment", action: "shipment_create"

    get "payment"
    patch "payment", action: "payment_create"

    get "confirm"
    patch "confirm", action: "confirm_create"

    get "complete"
  end

  # サロン情報
  resources :salons, only: [:index]

  # 裏側
  namespace :admin, module: :administration do

    # Admin root
    root to: "dashboard#index"

    # Setting
    resource :setting

    # Session
    delete "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    post "login" => "sessions#create"

    # プレスリリース
    resources :press_releases

    # Topics
    resources :topics

    # News
    resources :news_releases

    # 商品マスタ管理
    resources :products
    resources :categories
    resources :serieses
    resources :solutions

    # お客様の声
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]

    # 注文管理
    resources :orders, except: [:new, :create] do
      collection do
        post :update_status
      end
    end

    # 売上一覧
    resources :sales, only: [:index] do
      collection do
        get :products
      end
    end

    # 裏側ユーザ管理
    resources :administrators

    resources :consumers

    # デザインテンプレート編集
    resources :templates

    # ページ編集
    resources :pages

    # File Storage
    resources :file_storages

    # 代理店管理
    resources :agencies

    # マージン管理
    resources :margins, only: [:index, :show, :edit, :update]

    # サロン管理
    resources :salons

    # 情報編集
    resource :information, only: [:show, :edit, :update]

    # 報酬確認画面
    get "reward", to: "reward#show"
  end
end

app/models/cart.rb
# class Cart
class Cart < ActiveRecord::Base
  include Pricing
  include Regulating

  belongs_to :consumer
  has_many :items, class_name: 'CartItem', dependent: :delete_all
  has_many :products, through: :items

  def payment_type
    'Payment::Creditcard'
  end

  def status
    :cashier
  end

  def postage
    compute_postage
  end

  def commission
    compute_commission
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter :mobile_headerless!

  before_filter :set_product, only: [:add, :increment, :decrement, :remove]

  def index
    add_breadcrumb "ご注文手続き"
  end

  def add
    amount = params[:amount].to_i
    if @product.stock <= amount
      flash[:notice] = "在庫がありません"
      redirect_to action: :index and return
    end
    current_cart.add @product, amount
    redirect_to action: :index
  end

  def increment
    current_cart.increment @product
    redirect_to action: :index
  end

  def decrement
    current_cart.decrement @product
    redirect_to action: :index
  end

  def remove
    current_cart.remove @product
    redirect_to action: :index
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/add.html.slim
h1 Carts#add
p Find me in app/views/carts/add.html.slim

app/views/carts/index.html.slim
.main
  h1 = image_tag 'cashier/cart_line.png', alt: 'ショッピングカートを見る'

  - if current_cart.items.without_samples.count > 0
    p.mini 現在ショッピングカートには以下の商品が入っています。
    table.cart
      thead
        tr
          th.w40.product 商品名
          th.w10.capacity 容量
          th.w10.price 価格(税込)
          th.w10.amount 個数
          th.w10.total 小計(税込)
          th.w10.shipment 送料
          th.w10.remove

      tbody
        - current_cart.items.without_samples.each do |item|
          tr.item
            td.w40.product
              = image_tag item.product.image.url(:thumb)
              = item.product.name
            td.w10.capacity = raw item.product.capacity
            td.w10.price = number_to_currency item.view_origin_price
            td.w10.amount
              - if item.check_amount
                = form_tag add_carts_path(product_id: item.product.id), method: :post, class: 'autosend' do
                  = select_tag :amount, options_for_select((1..item.product.stock), selected: item.amount)
              - else
                = item.amount
            td.w10.total = number_to_currency item.price
            td.w10.shipment 別
            td.w10.remove
              = link_to remove_carts_path(product_id: item.product.id, amount: 1), method: :delete do
                = image_tag "cart/torikeshi_btn.jpg", alt: "取消"

        tr.no-border
          td.w70.results colspan=4 合計
          td.w10.total = number_to_currency current_cart.items_price
          td.w10.total = number_to_currency current_cart.postage
          td.w10.remove

        tr.no-border
          td.w70.results colspan=4 総合計
          td.w10.total
          td.w10.total = number_to_currency current_cart.total_price
          td.w10.remove

    p.cashier
      = link_to cashier_path do
        = image_tag 'cashier/kounyu_btn.jpg', alt: "ご注文手続き"

    p
      = link_to_back do
        = image_tag 'cart/back.jpg', alt: "ショッピングを続ける"


  - else
    p カートに商品がありません

.side = render 'side'

app/views/carts/index.mobile.slim
- if current_cart.items.without_samples.count > 0
  h2.belt カートに入っている商品
  ul.cart
    - current_cart.items.without_samples.each do |item|
      li.item
        .image = image_tag item.product.image.url(:item)
        .product = item.product.name
        .capacity = raw item.product.capacity
        .price
          | 価格(税込):
          = number_to_currency item.view_origin_price
        .amount
          - if item.check_amount
            = form_tag add_carts_path(product_id: item.product.id), method: :post, class: 'autosend inline' do
              | 数量
              '
              = select_tag :amount, options_for_select((1..item.product.stock), selected: item.amount)
          - else
            | 数量
            '
            = item.amount
          '
          = link_to remove_carts_path(product_id: item.product.id, amount: 1), method: :delete do
            = image_tag "cart/torikeshi_btn.jpg", alt: "取消"

    li.postage
      .name 送料
      .total = number_to_currency current_cart.postage

    li.total_price
      .name 総合計
      .total.big = number_to_currency current_cart.total_price

  p.actions
    = link_to cashier_path do
      = image_tag 'cashier/kounyu_btn.jpg', alt: "ご注文手続き"

  p.actions
    = link_to root_path do
      = image_tag 'cart/back.jpg', alt: "ショッピングを続ける"


- else
  p カートに商品がありません

app/views/carts/remove.html.slim
h1 Carts#remove
p Find me in app/views/carts/remove.html.slim