config/routes.rb
Commers::Application.routes.draw do

  get "sitemap/index"
  get "f/:filename", to: "file_storage#show"
  get "template/stylesheets/:key", to: "template#stylesheets"
  get "editable/stylesheets/:key", to: "editable#stylesheets"

  # メルマガユーザーエクスポート
  resources :mailmagazine_export, only: [:index]

  namespace :landing, path: 'land' do
    get :oioil, action: :oioil
  end

  # 表側ユーザ
  devise_scope :consumer do
    get "complete", to: "consumers/registrations#complete"
  end
  devise_for :consumers,
    path: 'mypage',
    controllers: {
      sessions: "sessions",
      registrations: "consumers/registrations",
      confirmations: "consumers/confirmations"
    }

  # トップページ
  controller :welcome do
    root action: "index"
    get "introduction", action: "introduction"
    get "about", action: "about"
    get "utilization", action: "utilization"
    get "faq", action: "faq"
    get "sitemap", action: "sitemap"
    get "company", action: "company"
    get "tradeinfo", action: "tradeinfo"
    get "privacypolicy", action: "privacypolicy"
    get "shops", action: "shops"
  end

  namespace :mypage do
    root action: :information
    patch "information", action: :update_information
  end

  # お問い合わせ
  controller :contact do
    get "contact", action: :new
    post "contact", action: :create
  end

  # 注文履歴
  resources :orders, only: [:index, :show, :edit, :update]

  # News
  resources :topics, only: [:index, :show]

  # プレスリリース
  resources :press_releases, only: [:index]

  # News
  resources :news_releases, only: [:index, :show]

  # 詳細ページ
  resources :products, only: [:index, :show] do
    collection do
      get 'newitems'
      get 'ranking'
    end
  end

  # 商品一覧
  namespace :catalog do
    get ":action/:id"
  end

  # レビュー
  resources :reviews, only: [:create]

  # カート
  resources :carts, only: [:index] do
    collection do
      post "add"
      patch "increment"
      patch "decrement"
      delete "remove"
    end
  end

  # 注文
  namespace :cashier do
    get "", action: "index"

    get "sample"
    patch "sample", action: "sample_create"

    get "shipment"
    patch "shipment", action: "shipment_create"

    get "payment"
    patch "payment", action: "payment_create"

    get "confirm"
    patch "confirm", action: "confirm_create"

    get "complete"
  end

  # サロン情報
  resources :salons, only: [:index]

  # 裏側
  namespace :admin, module: :administration do

    # Admin root
    root to: "dashboard#index"

    # Setting
    resource :setting

    # Session
    delete "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    post "login" => "sessions#create"

    # プレスリリース
    resources :press_releases

    # Topics
    resources :topics

    # News
    resources :news_releases

    # 商品マスタ管理
    resources :products
    resources :categories
    resources :serieses
    resources :solutions

    # お客様の声
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]

    # 注文管理
    resources :orders, except: [:new, :create] do
      collection do
        post :update_status
      end
    end

    # 売上一覧
    resources :sales, only: [:index] do
      collection do
        get :products
      end
    end

    # 裏側ユーザ管理
    resources :administrators

    resources :consumers

    # デザインテンプレート編集
    resources :templates

    # ページ編集
    resources :pages

    # File Storage
    resources :file_storages

    # 代理店管理
    resources :agencies

    # マージン管理
    resources :margins, only: [:index, :show, :edit, :update]

    # サロン管理
    resources :salons

    # 情報編集
    resource :information, only: [:show, :edit, :update]

    # 報酬確認画面
    get "reward", to: "reward#show"
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def series
    @catalog = Series.where(identify: params[:id]).first
    raise ActiveRecord::RecordNotFound unless @catalog
    title @catalog.name
    add_breadcrumb @catalog.name
    @products = @catalog.products.available
    @reviews = @catalog.reviews
    if params[:category]
      @products = @products
        .includes(:categories)
        .where(categories: { identify: params[:category] })
    end
    render 'show'
  end

  def category
    @catalog = Category.where(identify: params[:id]).first
    raise ActiveRecord::RecordNotFound unless @catalog
    title "#{@catalog.name}一覧"
    add_breadcrumb @catalog.name
    @products = @catalog.products.available
    @reviews = @catalog.reviews
    render 'show'
  end

  def solution
    @catalog = Solution.find(params[:id])
    raise ActiveRecord::RecordNotFound unless @catalog
    title "お悩み別−#{@catalog.name}"
    add_breadcrumb @catalog.name
    @products = @catalog.products.available
    @reviews = @catalog.reviews
    render 'show'
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/_authentic.html.slim
p
  = storage_image_tag 'authentic/howtouse.png'
  = storage_image_tag 'authentic/authentic.jpg'

app/views/catalog/_moreinside.html.slim
p  = storage_image_tag 'moreinside/keeplevel.jpg'
p  = storage_image_tag 'moreinside/mi_detail01.png'
p  = storage_image_tag 'moreinside/mi_detail02.png'
p  = storage_image_tag 'moreinside/mi_detail03.png'

app/views/catalog/_naturaltech.html.slim
/ p
/   = image_tag "catalog/naturaltech/explain1.png", alt: ""
/   = image_tag "catalog/naturaltech/explain2.png", alt: ""

p style="text-align: center;"
  = image_tag "catalog/naturaltech/explain1.png", alt: ""
  = image_tag "catalog/naturaltech/explain2.png", alt: ""

p style="text-align: center;border-bottom:4px solid #000;margin-bottom:20px;padding-bottom: 20px;"
  = image_tag "catalog/naturaltech/nt_6lineup.png", alt: ""

ul.natural6
  li = image_tag "catalog/naturaltech/nt_e.png", alt: ""
  li = image_tag "catalog/naturaltech/nt_d.png", alt: ""
  li = image_tag "catalog/naturaltech/nt_n.png", alt: ""
  li = image_tag "catalog/naturaltech/nt_c.png", alt: ""
  li = image_tag "catalog/naturaltech/nt_r.png", alt: ""
  li = image_tag "catalog/naturaltech/nt_w.png", alt: ""
p.annotation = image_tag "catalog/naturaltech/explanatory.png"
p style="clear: both; text-align: right;"
  = link_to catalog_path(action: :series, id: :naturaltech) do
    = image_tag "catalog/naturaltech/nt_index_btn.jpg", alt: "ナチュラルテック"

app/views/catalog/_oioil.html.slim
- if @catalog.identify == 'oioil'
  .pose = image_tag "catalog/category_oioil_txt.png", alt: ""

- if @catalog.identify == 'oioil'
  - @catalog.products.available.each do |product|
    = render partial: 'product', locals: { :@product => product }

app/views/catalog/_product_authentic.html.slim
.item class="#{@catalog.identify}-item #{product.template.identify}"
  .image = link_to product do
    = image_tag product.image.url(:item)
  .type
    span.kind = product.kind
    - product.parts.to_s.split(/\s/).each do |part|
      = image_tag "catalog/#{part}.png", alt: part
  .name = link_to product.name, product
  .label = strip_tags "【#{product.label_simple}】"
  .detail = product.small_detail
  p
    span.price
      = number_to_currency product.view_price
      small = "(税込)"
    span.capacity = raw product.capacity
  .navigate
    = link_to product, class: 'todetail' do
      = image_tag 'catalog/authentic/item_detail.jpg', alt: '詳しく見る'
    = link_to add_carts_path(product_id: product.id, amount: 1), method: :post, class: 'addcart' do
      = image_tag 'catalog/authentic/item_cartbtn.jpg', alt: 'カートに入れる'

app/views/catalog/_product_bigbottle.html.slim
.item class="#{@catalog.identify}-item #{product.template.identify} #{product.categories.pluck(:identify).join(' ')}"
  .image = link_to product do
    = image_tag product.image.url(:item)
  .name = link_to product.name, product
  .label = strip_tags "【#{product.label_simple}】"
  - if product.small_detail.present?
    .detail = product.small_detail
  .capacity = raw product.capacity
  .price
    = number_to_currency product.view_price
    small = "(税込)"
  .navigate
    = link_to product do
      = image_tag 'catalog/big_syousai.gif', alt: '詳しく見る'
    = link_to add_carts_path(product_id: product.id, amount: 1), method: :post do
      = image_tag 'catalog/big_cart.gif', alt: 'カートに入れる'

app/views/catalog/_product_kit.html.slim
.item class="#{@catalog.identify}-item #{product.template.identify}"
  .fukidashi = image_tag "catalog/kit/hukidashi_#{product.template.identify.gsub(/naturaltech_/, '')}.png"
  .image = link_to product do
    = image_tag product.image.url(:item)
  .name = link_to product.name, product
  .capacity = raw product.capacity
  .price
    = number_to_currency product.view_price
    small = "(税込)"
  .navigate
    = link_to product, class: 'todetail' do
      = image_tag 'catalog/authentic/item_detail.jpg', alt: '詳しく見る'
    = link_to add_carts_path(product_id: product.id, amount: 1), method: :post, class: 'addcart' do
      = image_tag 'catalog/authentic/item_cartbtn.jpg', alt: 'カートに入れる'

app/views/catalog/_product_moreinside.html.slim
.item class="#{@catalog.identify}-item #{product.template.identify}"
  .image = link_to product do
    = image_tag product.image.url(:item)
  .type
    - product.parts.to_s.split(/\s/).each do |part|
      = image_tag "catalog/#{part}.png", alt: part
    span.kind = product.kind
  .name = link_to product.name, product
  .label style="color: #{product.label_color}" = strip_tags product.label_simple
  .detail = product.small_detail
  .capacity = raw product.capacity
  .price
    = number_to_currency product.view_price
    small = "(税込)"
  .navigate
    = link_to product, class: 'todetail' do
      = image_tag 'catalog/naturaltech/item_detail.gif', alt: '詳しく見る'
    = link_to add_carts_path(product_id: product.id, amount: 1), method: :post, class: 'addcart' do
      = image_tag 'catalog/naturaltech/item_cartbtn.jpg', alt: 'カートに入れる'

app/views/catalog/_product_naturaltech.html.slim
.item class="#{@catalog.identify}-item #{product.template.identify} #{product.categories.pluck(:identify).join(' ')}"
  .image = link_to product do
    = image_tag product.image.url(:item)
  .type
    span.kind = product.kind
  .name = link_to product.name, product
  .label = strip_tags "【#{product.label_simple}】"
  - if product.small_detail.present?
    .detail = product.small_detail
  .capacity = raw product.capacity
  .price
    = number_to_currency product.view_price
    small = "(税込)"
  .navigate
    = link_to product, class: 'todetail' do
      = image_tag 'catalog/naturaltech/item_detail.gif', alt: '詳しく見る'
    = link_to add_carts_path(product_id: product.id, amount: 1), method: :post, class: 'addcart' do
      = image_tag 'catalog/naturaltech/item_cartbtn.jpg', alt: 'カートに入れる'

app/views/catalog/_product_oioil.html.slim
.item class="#{@catalog.identify}-item #{product.template.identify} #{product.categories.pluck(:identify).join(' ')}"
  .image = link_to product do
    = image_tag product.image.url(:item)
  .type
    span.kind = product.kind
  .name = link_to product.name, product
  - if product.small_detail.present?
    .detail = product.small_detail
  .capacity = raw product.capacity
  .price
    = number_to_currency product.view_price
    small = "(税込)"
  .navigate
    = link_to product, class: 'todetail' do
      = image_tag 'catalog/naturaltech/item_detail.gif', alt: '詳しく見る'
    = link_to add_carts_path(product_id: product.id, amount: 1), method: :post, class: 'addcart' do
      = image_tag 'catalog/naturaltech/item_cartbtn.jpg', alt: 'カートに入れる'

app/views/catalog/category.html.slim
h1 Catalog#category
p Find me in app/views/catalog/category.html.slim

app/views/catalog/show.html.slim
- if @catalog.identify == 'kit'
  = content_for :content_header do
    .catalog-header.travelkit
- elsif @catalog.identify == 'bigbottle'
- else
  = content_for :content_header do
    .catalog-header
      .container
        = image_tag "catalog/header_#{@catalog.identify}.jpg", alt: @catalog.name

.main

  - if %w|naturaltech moreinside|.include?(@catalog.identify)
    ul.category-select
      li = link_to "すべて", { category: nil }, class: (params[:category].nil? && "active")
      - (@catalog.identify == 'naturaltech' ? @catalog.categories : @catalog.categories.where(hidden: true)).load.each do |category|
        li = link_to category.name, { category: category.identify }, class: ((params[:category] == category.identify) && 'active')
  - elsif @catalog.identify == 'bigbottle'
    .bigbottle-header
      = image_tag "catalog/header_bigbottle.jpg"
  - else
    .spacing

  div class = "#{action_name}-items #{@catalog.identify}"
    = render partial: "product_#{@catalog.identify}", collection: @products, as: :product

  .catalog-page
    = render 'authentic'   if @catalog.identify == 'authentic'
    = render 'moreinside'  if @catalog.identify == 'moreinside'
    = render 'oioil'       if @catalog.identify == 'oioil'

    = render 'naturaltech' if @catalog.identify == 'naturaltech'

  h2 = image_tag 'welcome/ranking.png', alt: 'ランキング'
  = render 'ranking'

  h2 = image_tag 'welcome/media_line.png', alt: 'メディア掲載情報'
  = render 'media'

  - if @reviews.count > 0
    h2 = image_tag 'welcome/usercoment.png', alt: 'お客様の声'
    .reviews = render 'reviews'

  .hr

  h3 = image_tag 'products/otherproducts.jpg', alt: 'other products'
  ul.otherproducts
    li = link_to catalog_path(action: :category, id: 'kit') do
      = image_tag 'products/otherproducts_01.png', alt: ''
    li = link_to catalog_path(action: :series, id: 'naturaltech') do
      = image_tag 'products/otherproducts_03.png', alt: 'ナチュラルテック'
    li = link_to catalog_path(action: :series, id: 'authentic') do
      = image_tag 'products/otherproducts_04.png', alt: 'オーセンティック'
    li = link_to catalog_path(action: :series, id: 'oioil') do
      = image_tag 'products/otherproducts_05.png', alt: 'オイ オイル'
    li = link_to catalog_path(action: :series, id: 'moreinside') do
      = image_tag 'products/otherproducts_02.png', alt: 'モアインサイド'

.side = render 'side'

app/views/catalog/show.mobile.slim
.catalog-header
  = image_tag "mobile/catalog/h_#{@catalog.identify}.jpg", alt: @catalog.name

h2.belt = @catalog.name

- @catalog.products.available.each do |product|
  .product-item = link_to product do
    .image = image_tag product.image.url(:item), alt: product.name
    .information
      .name = product.name
      - if product.label.present?
        .label = strip_tags "【#{product.label_simple}】"
      .capacity = raw product.capacity
      .price
        = number_to_currency product.view_price
        span.small （税込）
      .more = image_tag 'mobile/application/more.gif'

app/views/catalog/solution.html.slim
h1 Catalog#solution
p Find me in app/views/catalog/solution.html.slim