config/routes.rb
Commers::Application.routes.draw do

  get "sitemap/index"
  get "f/:filename", to: "file_storage#show"
  get "template/stylesheets/:key", to: "template#stylesheets"
  get "editable/stylesheets/:key", to: "editable#stylesheets"

  # メルマガユーザーエクスポート
  resources :mailmagazine_export, only: [:index]

  namespace :landing, path: 'land' do
    get :oioil, action: :oioil
  end

  # 表側ユーザ
  devise_scope :consumer do
    get "complete", to: "consumers/registrations#complete"
  end
  devise_for :consumers,
    path: 'mypage',
    controllers: {
      sessions: "sessions",
      registrations: "consumers/registrations",
      confirmations: "consumers/confirmations"
    }

  # トップページ
  controller :welcome do
    root action: "index"
    get "introduction", action: "introduction"
    get "about", action: "about"
    get "utilization", action: "utilization"
    get "faq", action: "faq"
    get "sitemap", action: "sitemap"
    get "company", action: "company"
    get "tradeinfo", action: "tradeinfo"
    get "privacypolicy", action: "privacypolicy"
    get "shops", action: "shops"
  end

  namespace :mypage do
    root action: :information
    patch "information", action: :update_information
  end

  # お問い合わせ
  controller :contact do
    get "contact", action: :new
    post "contact", action: :create
  end

  # 注文履歴
  resources :orders, only: [:index, :show, :edit, :update]

  # News
  resources :topics, only: [:index, :show]

  # プレスリリース
  resources :press_releases, only: [:index]

  # News
  resources :news_releases, only: [:index, :show]

  # 詳細ページ
  resources :products, only: [:index, :show] do
    collection do
      get 'newitems'
      get 'ranking'
    end
  end

  # 商品一覧
  namespace :catalog do
    get ":action/:id"
  end

  # レビュー
  resources :reviews, only: [:create]

  # カート
  resources :carts, only: [:index] do
    collection do
      post "add"
      patch "increment"
      patch "decrement"
      delete "remove"
    end
  end

  # 注文
  namespace :cashier do
    get "", action: "index"

    get "sample"
    patch "sample", action: "sample_create"

    get "shipment"
    patch "shipment", action: "shipment_create"

    get "payment"
    patch "payment", action: "payment_create"

    get "confirm"
    patch "confirm", action: "confirm_create"

    get "complete"
  end

  # サロン情報
  resources :salons, only: [:index]

  # 裏側
  namespace :admin, module: :administration do

    # Admin root
    root to: "dashboard#index"

    # Setting
    resource :setting

    # Session
    delete "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    post "login" => "sessions#create"

    # プレスリリース
    resources :press_releases

    # Topics
    resources :topics

    # News
    resources :news_releases

    # 商品マスタ管理
    resources :products
    resources :categories
    resources :serieses
    resources :solutions

    # お客様の声
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]

    # 注文管理
    resources :orders, except: [:new, :create] do
      collection do
        post :update_status
      end
    end

    # 売上一覧
    resources :sales, only: [:index] do
      collection do
        get :products
      end
    end

    # 裏側ユーザ管理
    resources :administrators

    resources :consumers

    # デザインテンプレート編集
    resources :templates

    # ページ編集
    resources :pages

    # File Storage
    resources :file_storages

    # 代理店管理
    resources :agencies

    # マージン管理
    resources :margins, only: [:index, :show, :edit, :update]

    # サロン管理
    resources :salons

    # 情報編集
    resource :information, only: [:show, :edit, :update]

    # 報酬確認画面
    get "reward", to: "reward#show"
  end
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  extend ActiveModel::Translation
  include ActiveModel::Validations

  attr_accessor :type, :name, :name_kana, :email, :phone, :body

  validates :type, presence: true
  validates :name, presence: true
  validates :name_kana, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :body, presence: true

  def attributes= attrs
    attrs.each do |k, v|
      self.send "#{k}=", v
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_filter :mobile_headerless!

  before_filter :set_contact

  def new
    add_breadcrumb "お問い合わせ"
  end

  def create
    add_breadcrumb "お問い合わせ"
    @contact.attributes = contact_params
    if @contact.valid?
      if params[:confirm]
        render 'confirm'
      else
        ContactMailer.contact(@contact).deliver
      end
    else
      render 'new'
    end
  end

  private

  def set_contact
    @contact = Contact.new
  end

  def contact_params
    params.require(:contact).permit(:type, :name, :name_kana, :email, :phone, :body)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/confirm.html.slim
.main

  h1 = image_tag "contact/contact_line.png", alt: "お問い合わせ"

  strong お問い合わせフォーム
  p 下記の内容で送信いたします。よろしければ送信ボタンを押してください。

  = form_for @contact, url: contact_path, method: :post do |f|
    table
      tbody
        tr
          th お問い合わせ内容
          td
            = @contact.type
            = f.hidden_field :type
        tr
          th お名前
          td
            = @contact.name
            = f.hidden_field :name
        tr
          th フリガナ
          td
            = @contact.name_kana
            = f.hidden_field :name_kana
        tr
          th メールアドレス
          td
            = @contact.email
            = f.hidden_field :email
        tr
          th 電話番号
          td
            = @contact.phone
            = f.hidden_field :phone
        tr
          th 本文
          td
            = simple_format @contact.body
            = f.hidden_field :body
    .actions = f.submit "この内容で送信"

.side = render 'side'

app/views/contact/confirm.mobile.slim
h1.belt お問い合わせ

h2 お問い合わせフォーム

p 下記の内容で送信いたします。よろしければ送信ボタンを押してください。

= form_for @contact, url: contact_path, method: :post do |f|
  label お問い合わせ内容
  .field
    = @contact.type
    = f.hidden_field :type
  label お名前
  .field
    = @contact.name
    = f.hidden_field :name
  label フリガナ
  .field
    = @contact.name_kana
    = f.hidden_field :name_kana
  label メールアドレス
  .field
    = @contact.email
    = f.hidden_field :email
  label 電話番号
  .field
    = @contact.phone
    = f.hidden_field :phone
  label 本文
  .field
    = simple_format @contact.body
    = f.hidden_field :body
  .actions = f.submit "この内容で送信"

app/views/contact/create.html.slim
.main

  h1 = image_tag "contact/contact_line.png", alt: "お問い合わせ"

  p お問い合わせを受け付けました。

.side = render 'side'

app/views/contact/create.mobile.slim
h1.belt お問い合わせ

p お問い合わせを受け付けました。

app/views/contact/new.html.slim
.main

  h1 = image_tag "contact/contact_line.png", alt: "お問い合わせ"

  p
    | ダヴィネスダイレクトをご覧頂き、ありがとうございます。
    br
    | 商品に関するお問い合わせは、下記フォームに必要事項をご記入後、「送信内容を確認」ボタンを押して送信してください。
    br
    | 確認次第担当のものよりご連絡いたします。
    br
    = link_to "お問い合わせの前にこちらをご確認ください。", faq_path

  strong お問い合わせフォーム
  p
    | 英語・数字は必ず半角にてご記入ください。
    br
    | また、全ての項目を入力してください。

  = form_for @contact, url: contact_path, method: :post do |f|

    - if @contact.errors.any?
      #error_explanation
        h2 エラー内容をご確認ください。
        ul
          - @contact.errors.full_messages.each do |message|
            li = message

    table
      tbody
        tr
          th お問い合わせ内容
          td = f.select :type, %w|商品について お届け・配送について お支払いについて その他|
        tr
          th お名前
          td = f.text_field :name
        tr
          th フリガナ
          td = f.text_field :name_kana
        tr
          th メールアドレス
          td = f.text_field :email
        tr
          th 電話番号
          td = f.text_field :phone
        tr
          th 本文
          td = f.text_area :body
    = hidden_field_tag :confirm, true
    .actions = f.submit "送信内容を確認"

.side = render 'side'

app/views/contact/new.mobile.slim
h1.belt お問い合わせ

p
  | ダヴィネスダイレクトをご覧頂き、ありがとうございます。
  br
  | 商品に関するお問い合わせは、下記フォームに必要事項をご記入後、「送信内容を確認」ボタンを押して送信してください。
  br
  | 確認次第担当のものよりご連絡いたします。
  br
  = link_to "お問い合わせの前にこちらをご確認ください。", faq_path

h2 お問い合わせフォーム

= form_for @contact, url: contact_path, method: :post do |f|
  - if @contact.errors.any?
    #error_explanation
      h2 エラー内容をご確認ください。
      ul
        - @contact.errors.full_messages.each do |message|
          li = message

  .field
    label お問い合わせ内容
    = f.select :type, %w|商品について お届け・配送について お支払いについて その他|
  .field
    label お名前
    = f.text_field :name
  .field
    label フリガナ
    = f.text_field :name_kana
  .field
    label メールアドレス
    = f.text_field :email
  .field
    label 電話番号
    = f.text_field :phone
  .field
    label 本文
    = f.text_area :body, rows: 15
  = hidden_field_tag :confirm, true
  .actions = f.submit "送信内容を確認"